import React from 'react';

const LazyLoadComp: React.FC = () => {
  return (
    <div>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur at est non purus elementum tincidunt. Nulla facilisi. Duis malesuada, ligula sit amet interdum ullamcorper, odio nisl viverra urna, et cursus erat ex non nisi. Sed tincidunt mi non lorem posuere, nec pharetra nisi volutpat. Fusce eget quam nisl. Duis mollis quam orci, ut feugiat ipsum viverra id. Integer fringilla libero vel magna varius, ut fringilla lacus aliquet. Etiam lacinia posuere ipsum, nec venenatis justo. Nam vel odio fermentum, placerat quam et, posuere erat. Donec vehicula velit ut ante efficitur tincidunt. Integer a consectetur dui, nec efficitur orci. Mauris id eros ex. Nulla facilisi. Suspendisse posuere turpis in massa porttitor, quis tempus justo condimentum. Nullam consectetur sapien vel nunc ullamcorper, at laoreet turpis malesuada. Aenean auctor arcu sit amet massa fermentum malesuada.</p>
      <p>Sed et nulla facilisis, congue metus a, tincidunt elit. Nullam condimentum felis sit amet purus fermentum, id vehicula orci accumsan. Integer porttitor nisi sit amet felis cursus, id varius risus fringilla. Fusce porttitor lacinia scelerisque. Curabitur feugiat ligula ac tortor efficitur malesuada. Nulla facilisi. Mauris lacinia pharetra lectus, nec ultrices turpis mollis sit amet. Duis ornare bibendum libero, eget fermentum sapien consequat nec. Sed vel arcu tincidunt, mattis nulla sed, suscipit leo. Aenean tristique elit vel velit condimentum, vel sollicitudin arcu aliquet. Nam vel lorem at velit pellentesque dictum ut quis ligula. Nulla facilisi. Phasellus sed tellus orci. Proin viverra metus eu metus dictum, sed hendrerit dolor lacinia. Proin pharetra odio ut arcu tincidunt varius. Cras ultricies, justo in facilisis dapibus, justo est dapibus sapien, nec fringilla est mi nec turpis.</p>
      <p>Vestibulum non bibendum dui. Ut nec lacinia magna. Proin vehicula ipsum turpis, quis efficitur mi interdum non. Vivamus pulvinar ante vel ipsum vehicula, non elementum augue ultricies. Aenean mollis tempor turpis, ac pharetra enim. Nam ultricies, est eu tincidunt aliquet, leo nunc ultrices lacus, sed fermentum orci leo ut mauris. Phasellus laoreet dolor eu purus scelerisque, non tristique arcu consequat. Sed dictum, erat ac laoreet venenatis, nulla sem vestibulum justo, sit amet aliquet tortor enim a lorem. Maecenas malesuada nunc sed ante gravida, id congue est convallis. Quisque convallis tortor non augue dapibus, sed pharetra libero aliquam. Integer hendrerit, nulla vel laoreet tempor, tortor felis interdum felis, a ultrices sapien sapien at arcu. Suspendisse potenti. Mauris posuere purus quis neque sagittis interdum. Proin non fermentum est. Proin lobortis magna eget ligula blandit, at tincidunt justo dictum. Nulla et magna vel lectus facilisis finibus.</p>
    </div>
  );
};

export default LazyLoadComp;